---
name: Copy image manifest
description: Copy existing manifest to a new name, like a docker tag
inputs:
  source:
    description: Image/manifest to retag
    required: true
  targets:
    description: Image/manifest to retag, can be a comma seperated list
    required: true
  wait:
    description: Wait for the source to be available
    default: true

# https://github.com/sudo-bmitch/regclient-action/blob/main/regctl-installer/action.yml
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        url_ext=""
        case "${{ runner.os }}-${{ runner.arch }}" in
          Linux-X64)
            url_platform="linux-amd64"
            ;;
          Linux-ARM64)
            url_platform="linux-arm64"
            ;;
          macOS-X64)
            url_platform="darwin-amd64"
            ;;
          macOS-ARM64)
            url_platform="darwin-arm64"
            ;;
          Windows-X64)
            url_platform="windows-amd64"
            url_ext=".exe"
            ;;
          *)
            log_error "architecture not supported: ${{ runner.os }}-${{ runner.arch }}"
            exit 1
            ;;
        esac
        curl -sL "https://github.com/regclient/regclient/releases/latest/download/regctl-${url_platform}${url_ext}" >regctl${url_ext}
        chmod +x "regctl${url_ext}"
    - shell: bash
      if: inputs.wait
      run: |
        until regctl image inspect ${{ inputs.source }}; do
          echo "${{ inputs.source }} not yet available, retrying in 10s";
          sleep 10s;
        done;
    - shell: bash
      env:
        TARGETS: ${{ inputs.targets }}
      run: |
        for target in ${TARGETS//,/ }; do
          ./regctl${url_ext} image copy --verbosity=info ${{ inputs.source }} $target
        done
