---
name: Copy image manifest
description: Copy existing manifest to a new name, like a docker tag
inputs:
  source:
    description: Image/manifest to retag
    required: true
  target:
    description: Image/manifest to retag
    required: true

# runs:
#   using: docker
#   image: docker://ghcr.io/regclient/regctl:latest
#   # https://github.com/regclient/regclient/blob/main/docs/regctl.md
#   args:
#     - image
#     - copy
#     - --verbosity=info
#     - ${{ inputs.source }}
#     - ${{ inputs.target }}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        url_ext=""
        case "${{ runner.os }}-${{ runner.arch }}" in
          Linux-X64)
            url_platform="linux-amd64"
            ;;
          Linux-ARM64)
            url_platform="linux-arm64"
            ;;
          macOS-X64)
            url_platform="darwin-amd64"
            ;;
          macOS-ARM64)
            url_platform="darwin-arm64"
            ;;
          Windows-X64)
            url_platform="windows-amd64"
            url_ext=".exe"
            ;;
          *)
            log_error "architecture not supported: ${{ runner.os }}-${{ runner.arch }}"
            exit 1
            ;;
        esac
        curl -sL "https://github.com/regclient/regclient/releases/latest/download/regctl-${url_platform}${url_ext} >regctl${url_ext}"
        chmod +x "regctl${url_ext}"
    - shell: bash
      run: ./regctl${url_ext} image copy --verbosity=info ${{ inputs.source }} ${{ inputs.target }}
